
es= [
    "abeto", "actor", "aguas", "agudo", "alado", "albas", "altar", "Anton", "atizo", "avala",
    "avion", "azul", "abaco", "abate", "abeja", "aboya", "abran", "abras", "abria", "acoja",
    "acojo", "acres", "actas", "actos", "actuo", "acuna", "acune", "acuso", "acuso", "acuna",
    "afeas", "aguda", "agudo", "alaju", "alces", "aldea", "aleja", "algas", "alias", "almas",
    "altos", "amina", "andas", "andes", "anear", "anima", "anima", "atojo", "ayuda", "azote",
    "area", "anoro", "bache", "babas", "bacas", "bajes", "balas", "bebes", "belen", "Berto",
    "bicho", "bizco", "bueno", "buena", "busca", "bajos", "barre", "batas", "bates", "bayas",
    "banas", "banos", "bebed", "besen", "besos", "bojar", "bonos", "borre", "borra", "botad",
    "botes", "Bruno", "bruta", "bruto", "cabra", "cafes", "cajas", "calar", "calas", "calca",
    "calco", "calla", "calma", "camba", "campo", "canas", "cantos", "capto", "caras", "carga",
    "cargo", "Carlo", "carro", "casas", "catar", "Catar", "caida", "cejas", "Celia", "cenas",
    "cepas", "cerca", "cerco", "cerdo", "cerda", "chile", "Chile", "china", "China", "ciego",
    "ciega", "cinco", "cines", "cisne", "citas", "clara", "claro", "Clara", "clave", "clavo",
    "colas", "colon", "Colon", "coral", "coras", "corea", "Corea", "corro", "cosas", "costo",
    "coste", "crudo", "curdo", "curda", "curar", "celta", "coger", "combo", "corse", "crema",
    "cuida", "culos", "cural", "dados", "dagas", "datos", "danza", "dejar", "dejes", "denso",
    "densa", "dices", "divos", "dotes", "dunas", "dures", "duros", "Dubai", "enojo", "ellos",
    "ellas", "echas", "edito", "edita", "elevo", "emule", "enoje", "error", "errar", "estas",
    "Elena", "emoji", "envio", "erizo", "espia", "euros", "fallo", "falto", "feria", "fetos",
    "fijos", "filas", "filia", "finca", "firma", "floto", "focos", "folla", "forma", "Frida",
    "frita", "frito", "freir", "fugas", "fumas", "fusil", "Gales", "gafas", "galas", "Galia",
    "galos", "ganas", "ganes", "gases", "gasto", "girar", "gerbo", "gordo", "gorda", "gorro",
    "gorra", "grave", "grava", "grito", "gemir", "guera", "guero", "hacer",
    "halos", "hasta", "harta", "harto", "heces", "hielo", "habas", "habla", "hacha", "Haiti",
    "hijas", "hijos", "huera", "huero", "india", "indio", "ideas", "inflo", "islas", "India",
    "islas", "Ivana", "Japon", "jefas", "jefes", "jerga", "Josue", "juego", "jugar", "julio",
    "Julio", "Julia", "jadeo", "Jairo", "jalon", "jerbo", "Jesus", "joder", "jurar", "Kabul",
    "Kenia", "kurdo", "kurda", "labia", "lacra", "lados", "Lagos", "lance", "larg", "largo",
    "lejos", "lenta", "lento", "libia", "Libia", "libro", "libra", "linda", "lindo", "logro",
    "loteo", "luche", "liber", "mania", "malos", "malas", "marca", "marco", "Marco", "Marti",
    "marte", "marta", "Marta", "Maria", "Mario", "medio", "melon", "menos", "meter", "metro",
    "molar", "moler", "monte", "morir", "manco", "manca", "Malta", "mango", "manga",
    "meaba", "media", "midas", "Midas", "miras", "mirar", "miron", "mojar"
    "multa", "mundo", "nacer", "nadar", "narro", "natas", "naves", "necio", "necia", "ninos",
    "notas", "nubes", "Nuria", "nabos", "nazis", "Nepal", "nurdo", "nurda",
    "opera", "obras", "ocios", "ollas", "ondas", "onzas", "otros", "otras", "ovulo", "oirte",
    "oreja", "obras", "odiar", "orina", "ortos", "osito", "Paris", "palas", "pedir", "pelea",
    "pelos", "pelar", "peras", "perro", "perra", "pesos", "pilas", "pinto", "Pinto", "poder",
    "pacto", "pagar", "palma", "Palma", "Papua", "parda", "pardo", "paseo", "pateo", "pecio",
    "penes", "peres", "pesca", "pifia", "pisco", "playa", "pleno", "poner", "prada", "punto",
    "punta", "purga", "Qatar", "queda", "quedo", "quede", "quema", "quito", "queso",
    "quepa", "reloj", "rubio", "rubia", "rasco", "rasca", "ratas", "rasta", "ratos", "redes",
    "remar", "renos", "renta", "rabia", "rabos", "rabal", "Ramos", "Ramon", "raspa",
    "recio", "recia", "regio", "regia", "resto", "rugir", "rogar", "Rusia", "sabio", "sabia",
    "savia", "saber", "sacar", "salar", "salir", "selva", "sanar", "sopas", "secar", "serio",
    "seria", "situo", "sobar", "sonar", "subir", "sucio", "sucia", "siete", "sacra", "sajon",
    "salve", "salva", "salto", "salud", "Samoa", "santo", "santa", "sedar", "sexos", "segar",
    "siega", "siria", "Siria", "sobar", "sobre", "solar", "sonda", "soplo", "sonar", "Sudan",
    "sueno", "suiza", "Suiza", "sushi", "super", "tabla", "tacos", "Tania", "tapas", "tapar",
    "tazas", "telon", "tener", "tejer", "tenis", "terco", "terca", "terso", "tersa", "Texas",
    "tipos", "tiras", "Tirso", "todas", "todos", "tomar", "Tomas", "tonos", "tonto", "tonta",
    "toque", "torpe", "trote", "talar", "telar", "tarde", "temer", "tenia", "topar", "tocar",
    "tomar", "toser", "toner", "traer", "tumba", "Tunez", "unosa", "untes", "urbes",
    "Uribe", "urnas", "valer", "vacas", "vagos", "vagas", "valor", "veces", "vedas", "velas",
    "velar", "vemos", "verse", "verso", "venir", "verde", "vigor", "vivir", "volar", "votar",
    "vasco", "vasca", "vasto", "vasta", "viajes", "video", "wikis", "wones", "xolas",
    "Yemen", "yates", "yemas", "yendo", "yenes", "yesca", "yogur", "yugos", "zorro", "zorra",
    "zonas", "zurdo", "zurda", "zarca", "zebra", "zegri", "zeina", "zejel", "zocar", "zocas"
]

en = [
    "ABACK", "ABASE", "ABATE", "ABBEY", "ABIDE", "ABOUT", "ABOVE", "ABYSS", "ACRID", "ACTOR", "ACUTE", 
    "ADAPT", "ADMIT", "ADOBE", "ADOPT", "ADORE", "ADULT", "AFTER", "AGAIN", "AGAPE", "AGATE", "AGENT", 
    "AGILE", "AGING", "AGLOW", "AGONY", "AGREE", "AHEAD", "ALBUM", "ALIEN", "ALIKE", "ALIVE", "ALLOW", 
    "ALOFT", "ALONE", "ALOOF", "ALOUD", "ALPHA", "ALTAR", "ALTER", "AMASS", "AMBER", "AMISS", "AMPLE", 
    "ANGEL", "ANGER", "ANGRY", "ANODE", "ANTIC", "AORTA", "APART", "APHID", "APPLE", "APPLY", "APRON", 
    "APTLY", "ARBOR", "ARDOR", "ARGUE", "AROMA", "ASCOT", "ASIDE", "ASKEW", "ASSET", "ATOLL", "ATONE", 
    "AUDIO", "AUDIT", "AVAIL", "AVERT", "AWAIT", "AWAKE", "AWFUL", "AXIOM", "AZURE", "BACON", "BADGE", 
    "BADLY", "BAGEL", "BAKER", "BALSA", "BANAL", "BARGE", "BASIC", "BATHE", "BATON", "BATTY", "BAYOU", 
    "BEACH", "BEADY", "BEAST", "BEEFY", "BEGET", "BEGIN", "BEING", "BELCH", "BELIE", "BELLY", "BELOW", 
    "BENCH", "BERET", "BERTH", "BESET", "BINGE", "BIOME", "BIRCH", "BIRTH", "BLACK", "BLAME", "BLAND", 
    "BLEAK", "BLEED", "BLEEP", "BLIMP", "BLOCK", "BLOKE", "BLOND", "BLOWN", "BLUFF", "BLURB", "BLURT", 
    "BLUSH", "BOOBY", "BOOST", "BOOZE", "BOOZY", "BORAX", "BOUGH", "BRAID", "BRAKE", "BRASH", "BRAVE", 
    "BREAD", "BREAK", "BREED", "BRIAR", "BRIBE", "BRIDE", "BRIEF", "BRINE", "BRING", "BRINK", "BRISK", 
    "BROKE", "BROOK", "BROOM", "BROTH", "BRUSH", "BUGGY", "BUILD", "BUILT", "BULKY", "BULLY", "BUNCH", 
    "BURLY", "CABLE", "CACAO", "CACHE", "CANDY", "CANNY", "CANOE", "CAPER", "CARAT", "CARGO", "CAROL", 
    "CARRY", "CATCH", "CATER", "CAULK", "CAUSE", "CEDAR", "CHAFE", "CHAIN", "CHAMP", "CHANT", "CHARD", 
    "CHARM", "CHART", "CHEAT", "CHEEK", "CHEER", "CHEST", "CHIEF", "CHILD", "CHILL", "CHIME", "CHOIR", 
    "CHOKE", "CHORD", "CHUNK", "CHUTE", "CIDER", "CIGAR", "CINCH", "CIRCA", "CIVIC", "CLASS", "CLEAN", 
    "CLEAR", "CLEFT", "CLERK", "CLICK", "CLIMB", "CLING", "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOWN", 
    "CLUCK", "COACH", "COAST", "COCOA", "COLON", "COMET", "COMMA", "CONDO", "CONIC", "CORNY", "COULD", 
    "COUNT", "COURT", "COVET", "COWER", "COYLY", "CRAFT", "CRAMP", "CRANE", "CRANK", "CRASS", "CRATE", 
    "CRAVE", "CRAZE", "CRAZY", "CREAK", "CREDO", "CREPT", "CRIME", "CRIMP", "CROAK", "CRONE", "CROSS", 
    "CRUMB", "CRUST", "CUMIN", "CURLY", "CYNIC", "DADDY", "DAISY", "DANCE", "DANDY", "DEATH", "DEBUG", 
    "DECAY", "DECAL", "DELTA", "DELVE", "DENIM", "DEPOT", "DEPTH", "DEVIL", "DIARY", "DIGIT", "DINER", 
    "DISCO", "DITTO", "DODGE", "DOING", "DONOR", "DONUT", "DOUBT", "DOWRY", "DOZEN", "DRAIN", "DREAM", 
    "DRINK", "DRIVE", "DROLL", "DROOP", "DUCHY", "DUTCH", "DUVET", "DWARF", "DWELL", "DWELT", "EARLY", 
    "EARTH", "EBONY", "EGRET", "EJECT", "ELDER", "ELOPE", "ELUDE", "EMAIL", "EMBER", "EMPTY", "ENEMA", 
    "ENJOY", "ENNUI", "ENTER", "EPOCH", "EPOXY", "EQUAL", "EQUIP", "ERODE", "ERROR", "ERUPT", "ESSAY", 
    "ETHIC", "ETHOS", "EVADE", "EVERY", "EVOKE", "EXACT", "EXCEL", "EXERT", "EXIST", "EXPEL", "EXTRA", 
    "EXULT", "FACET", "FARCE", "FAULT", "FAVOR", "FEAST", "FEIGN", "FERRY", "FEWER", "FIELD", "FIEND", 
    "FIFTY", "FINAL", "FINCH", "FINER", "FIRST", "FISHY", "FIXER", "FJORD", "FLAIL", "FLAIR", "FLAME", 
    "FLANK", "FLARE", "FLASK", "FLESH", "FLICK", "FLING", "FLIRT", "FLOAT", "FLOCK", "FLOOD", "FLOOR", 
    "FLORA", "FLOSS", "FLOUT", "FLUFF", "FLUME", "FLYER", "FOCAL", "FOCUS", "FOGGY", "FOLLY", "FORAY", 
    "FORCE", "FORGE", "FORGO", "FORTH", "FORTY", "FOUND", "FOYER", "FRAME", "FRANK", "FRESH", "FRIED", 
    "FROCK", "FROND", "FRONT", "FROST", "FROTH", "FROZE", "FUNGI", "FUNNY", "GAMER", "GAMMA", "GAUDY", 
    "GAUZE", "GAWKY", "GECKO", "GENRE", "GHOUL", "GIANT", "GIDDY", "GIRTH", "GIVEN", "GLASS", "GLAZE", 
    "GLEAM", "GLEAN", "GLOAT", "GLOBE", "GLOOM", "GLORY", "GLOVE", "GLYPH", "GNASH", "GOLEM", "GONER", 
    "GOOSE", "GORGE", "GOUGE", "GRACE", "GRADE", "GRAIL", "GRAND", "GRAPH", "GRASP", "GRATE", "GREAT", 
    "GREEN", "GREET", "GRIEF", "GRIME", "GRIMY", "GRIPE", "GROIN", "GROUP", "GROUT", "GROVE", "GROWL", 
    "GRUEL", "GUANO", "GUARD", "GUEST", "GUIDE", "GUILD", "GULLY", "GUPPY", "HAIRY", "HAPPY", "HATCH", 
    "HATER", "HAVOC", "HEADY", "HEARD", "HEART", "HEATH", "HEAVE", "HEAVY", "HEIST", "HELIX", "HELLO", 
    "HERON", "HINGE", "HOARD", "HOBBY", "HOMER", "HORDE", "HORSE", "HOTEL", "HOUND", "HOUSE", "HOWDY", 
    "HUMAN", "HUMID", "HUMOR", "HUMPH", "HUNCH", "HUNKY", "HURRY", "HUTCH", "HYPER", "IGLOO", "IMAGE", 
    "IMPEL", "INANE", "INDEX", "INEPT", "INERT", "INFER", "INPUT", "INTER", "INTRO", "IONIC", "IRATE", 
    "IRONY", "ISLET", "ITCHY", "IVORY", "JAUNT", "JAZZY", "JERKY", "JOKER", "JOLLY", "JOUST", "JUDGE", 
    "KARMA", "KAYAK", "KAZOO", "KEBAB", "KHAKI", "KIOSK", "KNEEL", "KNELT", "KNOCK", "KNOLL", "KOALA", 
    "LABEL", "LABOR", "LAPEL", "LAPSE", "LARGE", "LARVA", "LASER", "LATTE", "LAYER", "LEAFY", "LEAKY", 
    "LEAPT", "LEARN", "LEASH", "LEAVE", "LEDGE", "LEERY", "LEGGY", "LEMON", "LIBEL", "LIGHT", "LILAC", 
    "LIMIT", "LINEN", "LINER", "LINGO", "LIVER", "LOCAL", "LOCUS", "LOFTY", "LOGIC", "LOOPY", "LOSER", 
    "LOUSE", "LOVER", "LOWLY", "LOYAL", "LUCID", "LUCKY", "LUNAR", "LUNCH", "LUNGE", "LUSTY", "LYING", 
    "MADAM", "MAGIC", "MAGMA", "MAIZE", "MAJOR", "MANIA", "MANLY", "MANOR", "MAPLE", "MARCH", "MARRY", 
    "MARSH", "MASON", "MASSE", "MATCH", "MATEY", "MAXIM", "MAYBE", "MAYOR", "MEALY", "MEANT", "MEDAL", 
    "MEDIA", "MERCY", "MERGE", "MERIT", "MERRY", "METAL", "METRO", "MICRO", "MIDGE", "MIDST", "MIMIC", 
    "MINCE", "MODEL", "MOIST", "MOLAR", "MONEY", "MONTH", "MOOSE", "MOSSY", "MOTOR", "MOTTO", "MOULT", 
    "MOUNT", "MOURN", "MOUSE", "MOVIE", "MUCKY", "MUMMY", "MURAL", "MUSIC", "MUSTY", "NAIVE", "NANNY", 
    "NASTY", "NATAL", "NAVAL", "NEEDY", "NEVER", "NIGHT", "NINJA", "NINTH", "NOBLE", "NOISE", "NORTH", 
    "NYMPH", "OCCUR", "OCEAN", "OFFAL", "OFTEN", "OLDER", "OLIVE", "ONION", "ONSET", "OPERA", "OTHER", 
    "OUGHT", "OUTDO", "OUTER", "OVERT", "OXIDE", "PANEL", "PANIC", "PAPER", "PARER", "PARRY", "PARTY", 
    "PASTA", "PATTY", "PAUSE", "PEACE", "PEACH", "PERCH", "PERKY", "PESKY", "PHASE", "PHONE", "PHONY", 
    "PHOTO", "PIANO", "PICKY", "PIETY", "PILOT", "PINEY", "PINKY", "PINTO", "PIOUS", "PIPER", "PIQUE", 
    "PITHY", "PIXEL", "PIXIE", "PLACE", "PLAIT", "PLANK", "PLANT", "PLATE", "PLAZA", "PLEAT", "PLUCK", 
    "PLUNK", "POINT", "POISE", "POKER", "POLKA", "POLYP", "POUND", "POWER", "PRICE", "PRICK", "PRIDE", 
    "PRIME", "PRIMO", "PRINT", "PRIZE", "PROBE", "PROVE", "PROWL", "PROXY", "PRUNE", "PSALM", "PULPY", 
    "PURGE", "QUALM", "QUART", "QUEEN", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIET", "QUIRK", "QUOTE", 
    "RADIO", "RAINY", "RAISE", "RAMEN", "RANCH", "RANGE", "RATIO", "RAYON", "REACT", "REALM", "REBUS", 
    "REBUT", "RECAP", "REGAL", "RELIC", "RENEW", "REPAY", "REPEL", "RESIN", "RETCH", "RETRO", "RETRY", 
    "REVEL", "RHINO", "RHYME", "RIDGE", "RIGHT", "RIPER", "RISEN", "RIVAL", "ROBIN", "ROBOT", "ROCKY", 
    "RODEO", "ROGUE", "ROOMY", "ROUGE", "ROUND", "ROUSE", "ROUTE", "ROVER", "ROYAL", "RUDDY", "RUDER", 
    "RUPEE", "RUSTY", "SAINT", "SALAD", "SALLY", "SALSA", "SALTY", "SASSY", "SAUTE", "SCALD", "SCANT", 
    "SCARE", "SCARF", "SCOLD", "SCOPE", "SCORN", "SCOUR", "SCOUT", "SCRAM", "SCRAP", "SCRUB", "SEDAN", 
    "SEEDY", "SENSE", "SERUM", "SERVE", "SEVER", "SHADE", "SHAKE", "SHALL", "SHAME", "SHANK", "SHARD", 
    "SHARP", "SHAWL", "SHAVE", "SHIFT", "SHINE", "SHIRE", "SHIRK", "SHORN", "SHOWN", "SHOWY", "SHRUB", 
    "SHRUG", "SHYLY", "SIEGE", "SIGHT", "SINCE", "SISSY", "SKILL", "SKIMP", "SKIRT", "SKUNK", "SLATE", 
    "SLEEK", "SLEEP", "SLICE", "SLOPE", "SLOSH", "SLOTH", "SLUMP", "SLUNG", "SMALL", "SMART", "SMASH", 
    "SMEAR", "SMELT", "SMILE", "SMIRK", "SMITE", "SMITH", "SNACK", "SNAFU", "SNAIL", "SNAKE", "SNAKY", 
    "SNARE", "SNARL", "SNEAK", "SNORT", "SNOUT", "SOGGY", "SOLAR", "SOLID", "SOLVE", "SONIC", "SOUND", 
    "SOWER", "SPACE", "SPADE", "SPEAK", "SPELL", "SPELT", "SPEND", "SPENT", "SPICE", "SPICY", "SPIEL", 
    "SPIKE", "SPILL", "SPIRE", "SPLAT", "SPOKE", "SPRAY", "SPURT", "SQUAD", "SQUAT", "STAFF", "STAGE", 
    "STAID", "STAIR", "STALE", "STAND", "START", "STASH", "STATE", "STEAD", "STEED", "STEEL", "STEIN", 
    "STICK", "STIFF", "STILL", "STING", "STINK", "STOCK", "STOLE", "STOMP", "STONE", "STONY", "STOOL", 
    "STORE", "STORY", "STOUT", "STOVE", "STRAP", "STRAW", "STUDY", "STUNG", "STYLE", "SUGAR", "SULKY", 
    "SURER", "SURLY", "SUSHI", "SWEAT", "SWEEP", "SWEET", "SWILL", "SWINE", "SWIRL", "SYRUP", "TABLE", 
    "TABOO", "TACIT", "TAKEN", "TALON", "TANGY", "TAPER", "TAPIR", "TARDY", "TASTE", "TASTY", "TAUNT", 
    "TAWNY", "TEARY", "TEASE", "TEMPO", "TENTH", "TEPID", "THEIR", "THEME", "THERE", "THESE", "THIEF", 
    "THING", "THINK", "THIRD", "THORN", "THOSE", "THREE", "THREW", "THROW", "THUMB", "THUMP", "THYME", 
    "TIARA", "TIBIA", "TIDAL", "TIGER", "TILDE", "TIPSY", "TITHE", "TODAY", "TONIC", "TOPAZ", "TOPIC", 
    "TORSO", "TOTEM", "TOUCH", "TOUGH", "TOWEL", "TOXIC", "TOXIN", "TRACE", "TRACT", "TRADE", "TRAIN", 
    "TRAIT", "TRASH", "TRAWL", "TREAT", "TREND", "TRIAD", "TRICE", "TRITE", "TROLL", "TROPE", "TROVE", 
    "TRUSS", "TRUST", "TRUTH", "TRYST", "TWANG", "TWEAK", "TWEED", "TWICE", "TWINE", "TWIRL", "ULCER", 
    "ULTRA", "UNCLE", "UNDER", "UNDUE", "UNFED", "UNFIT", "UNIFY", "UNITE", "UNLIT", "UNMET", "UNTIE", 
    "UNTIL", "UNZIP", "UPSET", "URBAN", "USAGE", "USHER", "USING", "USUAL", "USURP", "UTTER", "VAGUE", 
    "VALET", "VALUE", "VALID", "VAPID", "VENOM", "VERGE", "VERVE", "VIGOR", "VIOLA", "VIRAL", "VITAL", 
    "VIVID", "VODKA", "VOICE", "VOILA", "VOTER", "VOUCH", "WACKY", "WALTZ", "WASTE", "WATCH", "WEARY", 
    "WEDGE", "WHACK", "WHALE", "WHEEL", "WHELP", "WHERE", "WHICH", "WHIFF", "WHILE", "WHINE", "WHINY", 
    "WHIRL", "WHISK", "WHOOP", "WINCE", "WINDY", "WOKEN", "WOMAN", "WOOER", "WORDY", "WORLD", "WORRY", 
    "WORSE", "WORST", "WOULD", "WOVEN", "WRATH", "WRIST", "WRITE", "WRONG", "WROTE", "WRUNG", "YACHT", 
    "YEARN", "YIELD", "YOUNG", "YOUTH", "ZESTY"
]